#if !canImport(ObjectiveC)
import XCTest

extension DisplaysTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DisplaysTests = [
        ("testMain", testMain),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(DisplaysTests.__allTests__DisplaysTests),
    ]
}
#endif
