name: Tests

on: [push, pull_request]

jobs:
    
    macOS:
        name: macOS
        runs-on: macOS-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Swift Version
          run: swift --version
        - name: Make Logs Directory
          run: mkdir logs
        - name: Build (Debug)
          run: swift build -v -c debug
        - name: Build (Release)
          run: swift build -v -c release
        - name: Test (Debug)
          run: swift test -v -c debug 
        - name: Test (Release)
          run: swift test -v -c release -Xswiftc -enable-testing
        - name: Upload Logs
          uses: actions/upload-artifact@v1
          with:
            name: logs
            path: logs
        - name: Slack Notification
          uses: elegantchaos/slatify@master
          if: always()
          with:
            type: ${{ job.status }}
            job_name: 'macOS'
            mention_if: 'failure'
            url: ${{ secrets.SLACK_WEBHOOK }}

